<?php

namespace PsychoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PsychoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PsychoRepository extends EntityRepository
{
}
